<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Nitro5" failures="1" tests="6" name="Test" time="21.36" errors="0" timestamp="2025-09-11T10:16:00 IST">
  <testcase classname="testscript.LoginTest" name="verifyLoginWithValidCredentials" time="1.736">
    <skipped/>
  </testcase> <!-- verifyLoginWithValidCredentials -->
  <testcase classname="testscript.LoginTest" name="verifyLoginWithValidCredentials" time="0.788">
    <skipped/>
  </testcase> <!-- verifyLoginWithValidCredentials -->
  <testcase classname="testscript.LoginTest" name="verifyLoginWithValidCredentials" time="0.706">
    <failure type="java.lang.AssertionError" message="Login is not sucessfull expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]">
      <![CDATA[java.lang.AssertionError: Login is not sucessfull expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at testscript.LoginTest.verifyLoginWithValidCredentials(LoginTest.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithValidCredentials -->
  <testcase classname="testscript.LoginTest" name="verifyLoginWithValidUsernameInvalidpassword" time="0.874"/>
  <testcase classname="testscript.LoginTest" name="verifyLoginWithInvalidUsernameValidpassword" time="0.756"/>
  <testcase classname="testscript.LoginTest" name="verifyLoginWithInvalidUsernameInvalidpassword" time="0.781"/>
</testsuite> <!-- Test -->
